### ISSUE TITLE
Starting issues

### ISSUE THREAD

**Issue by kamekazz** [Simply007/cloud-sample-app-intranet-gatsby#5]
Having difficulty starting the project. How do I start this project if I don't have yarn?

**Comment by Simply007** [comment]
Hello @kamekazz,

`yarn` should not be necessary to run the starter.
You could just clone the repository and use `npm` to install dependencies and run the sample.

Following the [quick start should be sufficient](https://github.com/Simply007/kontent-sample-app-gatsby-intranet#-quick-start).

**Comment by kamekazz** [comment]
Oh, I really apologize. I was using npm start.
